name: ops-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - myst-nb
  - openjdk=11
  - plotly
  - sphinx
  - sphinx_rtd_theme

  - pip
  - pip:
      - sphinx-multiproject
      - sphinxcontrib-jquery
      - readthedocs-sphinx-search
      - sphinx-tabs
      - sphinx_charts
