# Use this file to construct an environment for
# working with ImageJ Ops2 in a runtime setting.
#
# First, install mambaforge:
#
#   https://github.com/conda-forge/miniforge#mambaforge
#
# Then run:
#
#   mamba env create
#   mamba activate imagej-ops2
#
# It includes the dependencies needed for using ImageJ Ops2, but not tools
# for developer-related actions like running automated tests (pytest),
# linting the code (black), and generating the API documentation (sphinx).

name: imagej-ops2
channels:
  - conda-forge
  - defaults
dependencies:
  - python >= 3.7
  # Project dependencies
  - jupyter
  - openjdk >= 17
  - scyjava
  # Project from source
  - pip
