package templates.adapt.complexLift

import main.plusAssign
import templates.Globals
import java.io.File

class FunctionsToComputersAndLift(sourceDir: File) : Globals(sourceDir,
                                                             "org/scijava/ops/engine/adapt/complexLift",
                                                             "FunctionsToComputersAndLift") {

    val arities = 1..maxArity

    fun iterableGenerics(arity: Int) = "<${genericParamTypes(arity).joinToString { "Iterable<$it>" }}>"

    fun classGenerics(arity: Int) = "<I, ${genericParamTypes(arity).joinToString()}>"

    fun iteratorsHaveNext(arity: Int) = when (arity) {
        0 -> "itrout.hasNext()"
        1 -> "itrin.hasNext() && itrout.hasNext()"
        else -> "${(1..arity).joinToString(" && ") { "itrin$it.hasNext()" }} && itrout.hasNext()"
    }

    fun iteratorsNext(arity: Int) = when (arity) {
        0 -> "itrout.next()"
        1 -> "itrin.next(), itrout.next()"
        else -> "${(1..arity).joinToString { "itrin$it.next()" }}, itrout.next()"
    }

    fun inputArgs(arity: Int) = (1..arity).joinToString { "in$it" }

    fun iteratorCtor(arity: Int): List<String> = when (arity) {
        0 -> emptyList()
        1 -> listOf("Iterator<I> itrin = in.iterator();")
        else -> (1..arity).map { "Iterator<I$it> itrin$it = in$it.iterator();" }
    } + "Iterator<O> itrout = out.iterator();"


    override fun generate(text: StringBuilder) {
        text += """/*
 * #%L
 * SciJava Operations: a framework for reusable algorithms.
 * %%
 * Copyright (C) 2016 - 2019 SciJava Ops developers.
 * %%
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */

/*
* This is autogenerated source code -- DO NOT EDIT. Instead, edit the
* corresponding template in templates/ and rerun bin/generate.groovy.
*/

package org.scijava.ops.engine.adapt.complexLift;

import java.util.function.BiFunction;
import java.util.function.Function;

import org.scijava.Priority;
import org.scijava.function.Computers;
import org.scijava.function.Functions;
import org.scijava.ops.spi.OpDependency;
import org.scijava.ops.spi.Op;
import org.scijava.ops.spi.OpClass;

/**
 * Collection of adaptation Ops to convert {@link Functions} into
 * {@link Computers} with the use of a {@link Function} that copies the output
 * using the first input as a model.
 * 
 * @author Gabriel Selzer
 */
public class FunctionsToComputersAndLift {"""

        for (arity in 1..maxArity)
            text += """
	@OpClass(names = "adapt", priority = Priority.LOW)
	public static class Function${arity}ToComputer${arity}AndLiftAfter${generics(arity)} implements
		Function<${functionArity(arity)}${generics(arity)}, ${computerArity(arity)}${iterableGenerics(arity)}>,
		Op
	{

		@OpDependency(name = "adapt", adaptable = false)
		Function<${functionArity(arity)}${generics(arity)}, ${computerArity(arity)}${generics(arity)}> adaptor;
		@OpDependency(name = "adapt", adaptable = false)
		Function<${computerArity(arity)}${generics(arity)}, ${computerArity(arity)}${iterableGenerics(arity)}> lifter;

		/**
		 * @param function - the Function to convert
		 * @return the function as a Computer
		 */
		@Override
		public ${computerArity(arity)}${iterableGenerics(arity)} apply(
			${functionArity(arity)}${generics(arity)} function)
		{
			return lifter.apply(adaptor.apply(function));
		}

	}

	@OpClass(names = "adapt", priority = Priority.LOW + 1)
	public static class Function${arity}ToComputer${arity}AndLiftBefore${generics(arity)} implements
		Function<${functionArity(arity)}${generics(arity)}, ${computerArity(arity)}${iterableGenerics(arity)}>,
		Op
	{

		@OpDependency(name = "adapt", adaptable = false)
		Function<${functionArity(arity)}${iterableGenerics(arity)}, ${computerArity(arity)}${iterableGenerics(arity)}> adaptor;
		@OpDependency(name = "adapt", adaptable = false)
		Function<${functionArity(arity)}${generics(arity)}, ${functionArity(arity)}${iterableGenerics(arity)}> lifter;

		/**
		 * @param function - the Function to convert
		 * @return the function as a Computer
		 */
		@Override
		public ${computerArity(arity)}${iterableGenerics(arity)} apply(
			${functionArity(arity)}${generics(arity)} function)
		{
			return adaptor.apply(lifter.apply(function));
		}

	}"""

        text += "}"
    }
}